apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - api.yaml
  - worker.yaml
  - qdrant.yaml
  - migration.yaml
  - scaling.yaml
images:
  - name: rag-service
    newName: rag-service
    newTag: latest
