apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - dependencies.yaml
patches:
  - path: patch.yaml
images:
  - name: rag-service
    newName: rag-service
    newTag: local
